export const GeneralInitialValues = {
    productName: 'test',
    mrp: 1,
    sku: 'sku',
    barcode: '',
    brand: '',
    keywords: '',
    minQty: 1,
    weight: 0,
    height: '',
    length: '',
    width:"",
    dimensions: '',
    taxSlab: [],
    status: false,
    todaysDeal: false,
    featured:false,
    description: '',
    isCess: false,
    cess: [],
    // ===== File upload section =================
    galleryImages: [],
    thumbnails:[],
    // productImages: [],
    sizeImages: [],
    // ===== price stock section =================
    
    basePrice:null,
    samplePrice:null,
    discount:null,
    discountType:"",
    pricePerPieces:[],
    selectWise:"",
    store:"",
    variations:[],
    
  }